---
- hosts: all
  become: true
      
  tasks:

    - name: Installing Zabbix apt-package
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        name: zabbix-agent
        update_cache: yes        

    - name: Copying local zabbix-fms-config
      copy:
        src: "../../files/zabbix/fms_config.py"
        dest: "/etc/zabbix/scripts/fms_config.py"
        owner: root
        group: root
        mode: "0644"

    - name: Copying local zabbix-CheckBackups
      copy:
        src: "../../files/zabbix/CheckBackups.sh"
        dest: "/etc/zabbix/scripts/CheckBackups.sh"
        owner: root
        group: root
        mode: "0644"