---
- hosts: all
  become: true
  
  vars:
    aws_access_key: "AKIATXKUB4EBE2PRIVO4"
    aws_secret_key: "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"
    aws_region: "eu-north-1"
    aws_format: "text"

  tasks:

    - name: Installning unzip
      ansible.builtin.apt:
            name: unzip
            state: present
        
    - name: Download AWS-cli & unzip
      unarchive:
        src: "{{ 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' if ansible_architecture == 'x86_64' else 'https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip' }}"
        dest: /tmp
        list_files: yes
        remote_src: True
      register: unarchive_result

    - name: Installing awscli package.
      ansible.builtin.shell: "/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update"
      become_user: "root"

    - name: Configure AWS.
      ansible.builtin.shell: aws configure set {{ item.key }} {{ item.value }} 
      no_log: True
      with_dict:
        aws_access_key_id: "{{ aws_access_key }}"
        aws_secret_access_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        format: "{{ aws_format }}"
      changed_when: false
      
    - name: Removing temp install files
      ansible.builtin.file:
        path: /tmp/aws
        state: absent
        
    - name: copying local backup-script to server
      copy:
        src: "../../files/backup_to_s3.sh"
        dest: "/usr/local/bin/backup_to_s3.sh"
        owner: root
        group: root
        mode: "a+x"
        
    - name: Seting up cron for backup-script
      ansible.builtin.cron:
        name: "Amazon S3 backup twice a day"
        minute: "0"
        hour: "13,1"
        job: "/usr/local/bin/backup_to_s3.sh -d /fms-data/backup/backup/Daily/ -f /fms-data/container/"